const EmulationResources = {
  VN: {
    Employee: "Nhân viên",
    Summary: "Tổng quan",
    Customer: "Khách hàng",
    EmulationTitle: "Danh hiệu thi đua",
    Filter: "Bộ lọc",
    AddEmulation: "Thêm danh hiệu",
    EnterCodeOrTitle: "Nhập mã hoặc tên danh hiệu",
    Selected: "Đã chọn",
    Uncheck: "Bỏ chọn",
    Use: "Sử dụng",
    NotUse: "Ngừng sử dụng",
    Delete: "Xóa",
    Minimize: "Thu gọn",
    Confirm: "Xác nhận",
    Cancel: "Hủy",
    EditEmulation: "Sửa danh hiệu thi đua",
    AddNewEmulation: "Thêm danh hiệu thi đua",
    NameEmulation: "Tên danh hiệu thi đua",
    CodeEmulation: "Mã danh hiệu",
    FillName: "Nhập tên danh hiệu thi đua",
    RequireName: "Tên danh hiệu thi đua không được để trống",
    RequireCode: "Mã danh hiệu không được để trống",
    ObjectEmulation: "Đối tượng khen thưởng",
    Individual: "Cá nhân",
    Collective: "Tập thể",
    Require: "Vui lòng chọn",
    LevelEmulation: "Cấp khen thưởng",
    SelectLevel: "  Chọn cấp bậc khen thưởng",
    Government: "Cấp nhà nước",
    Town: "Cấp xã",
    Province: "Cấp tỉnh",
    District: "Cấp huyện",
    RequireLevel: "Vui lòng chọn cấp khen thưởng",
    Type: "Loại phong trào ",
    Permanent: "Thường xuyên",
    Batches: "Theo đợt",
    Note: "Ghi chú",
    SaveAdd: "Lưu & Thêm mới",
    Save: "Lưu",
    Status: "Trạng thái",
    NotDataFount: " Không có dữ liệu ",
    Total: "Tổng số",
    DataPerPage: "Số bản ghi/ trang  ",
    Data: "Bản ghi",
    Notification: "Thông báo",
    AgreeToChange: "Dữ liệu đã bị thay đổi, bạn có muốn lưu lại không?",
    Not: "Không",
    UpdateEmulation: "Sửa danh hiệu",
    DeleteEmulation: "Xóa danh hiệu",
    Decision: "Bạn có chắc chắn muốn xóa danh hiệu",
    All: "Tất cả",
    Instruct: "Hướng dẫn",
    Close: "Đóng",
    AlreadyExistCode: "Mã danh hiệu đã tồn lại, vui lòng chọn mã khác",
    SaveChange: "Lưu thay đổi",
    FilterEmulation: "Lọc danh hiệu",
    Apply: "Áp dụng",
    Import: "Nhập khẩu",
    ChooseFileImport: "Chọn tệp nhập khẩu",
    ChooseFile: "Kéo thả tệp vào đây hoặc nhập để chọn tệp",
    SupportFile: "Hỗ trợ định dạng *.xls, *.xlsx và kích thước tối đa 5MB",
    DowloadEx: "Tải tệp mẫu",
    Continue: "Tiếp tục",
    Return: "Quay lại",
  },
};
export default EmulationResources;
